### ISSUE TITLE
Service 4 : Facebook

### ISSUE THREAD

**Issue by Tech0ne** [EPITECH-ESPEEN/ESPEEN#20]
### **Consignes :**

- Mettre en place un nouveau service où un utilisateur pourra se connecter
- Ce service pourra être ajouté à un utilisateur lorsqu'il y sera connecté
- L'utilisateur pourra choisir une action et/ou une réaction lié à ce service à partir de la page AREA et l'interconnecté à d'autres services en fonction

### **Objectifs :**

- [x] Connexion api Facebook
- [ ] Action : Gestion de fil d'actualité
- [ ] Reaction : Publication d'un tweet
- [x] Relier a la db
- [ ] Creer le serviceRouter pour webhook

**Comment by Dan13615** [comment]
Les actions et reactions a l'aide du service META sont indisponible en raison du statut de societe et du portefeuille entreprise que nous ne possedons pas, par consequent ce service n'est disponible que pour l'OAuth2
