### ISSUE TITLE
Mobile : Page AREA logic

### ISSUE THREAD

**Issue by Aeliondw** [EPITECH-ESPEEN/ESPEEN#34]
## **Page : Area**
**Dépendant du ticket [#5](https://github.com/EPITECH-ESPEEN/ESPEEN/issues/5)**

### **Consignes :** 

- Il faut que l'utilisateur puisse à terme personnaliser les différentes intéractions entre les APIs

### **Objectifs :**

- [ ] Avoir des nodes modulables 
- [x] Récupérer les différents services, actions, réactions existant dans le serveur

[Source Figma](https://www.figma.com/design/hbwBqhL4lSyg36B5zLEJYv/Area---Espeen?node-id=0-1&node-type=canvas&t=nOO1WhJ56J5v3pk1-0)

**Comment by dragusheen** [comment]
pas de nodes, impossible à mettre en place sur le mobile
