### ISSUE TITLE
Design Prototype

### ISSUE THREAD

**Issue by Aeliondw** [EPITECH-ESPEEN/ESPEEN#4]
Le but est d'avoir un premier design de l'application des clients web et mobile afin de : 

- Harmoniser les idées de toute l'équipe 
- Visualiser et tester l'interface utilisateur avant le développement complet
- Identifier les problèmes potentiels tôt dans le processus
- Communiquer clairement les attentes entre tous les développeurs
- Affiner l'expérience utilisateur dès le début du projet

Objectifs : 

- [x] Maquette Figma

**Comment by dragusheen** [comment]
https://www.figma.com/design/hbwBqhL4lSyg36B5zLEJYv/Area---Espeen?node-id=0-1&t=vZARBhFIBfsFFZ7K-1
