### ISSUE TITLE
Service 1 Google : Login in ESPEEN with OAuth2

### ISSUE THREAD

**Issue by Dan13615** [EPITECH-ESPEEN/ESPEEN#8]
## **Feature : Authentification via OAuth2 d'un utilisateur sur notre service**
**Dépendant du ticket #5, #7, #30** 

### **Consignes :** 

-  Une méthode d'identification des utilisateurs via OAuth2 (ex : Google / X / Facebook / etc.). Dans ce cas, le client traite lui-même cette identification et prévient le serveur d'application en cas de succès.
- Concernant la méthode d'identification, pensez à connecter le compte tiers à un utilisateur du système.

### **Objectifs :** 

- [x]  Récupérer 1 API (minimum) au choix pour une méthode d'identification via OAuth2
- [x] Login l'utilisateur si existant
- [x] Gestion d'erreur si le compte tiers est inexistant dans la db

**Comment by Dan13615** [comment]
Je teste d'utiliser la google API qui pourra etre reutiliser comme service, et est la methode la plus rependu pour de l'OAuth2

**Comment by Aeliondw** [comment]
Je rajoute Léo comme son ticket #26 est lié à celui-ci
